---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-role-slack-fedora-26
    image: fedora:26
  - name: ansible-role-slack-centos-7
    image: centos:7
  - name: ansible-role-slack-ubuntu-xenial
    image: ubuntu:xenial
  - name: ansible-role-slack-ubuntu-yakkety
    image: ubuntu:yakkety
  - name: ansible-role-slack-ubuntu-zesty
    image: ubuntu:zesty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
