---
#// Add flash support from here: https://www.if-not-true-then-false.com/2010/install-adobe-flash-player-10-on-fedora-centos-red-hat-rhel/

- name: Copy Bashrc into place
  template:
    src: "bashrc.j2"
    dest: "/home/{{ ansible_user }}/.bashrc"

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install the 'Development tools' package group
  dnf:
    name: '@Development tools'
    state: present

- name: install the 'virtualization' package group
  dnf:
    name: '@virtualization'
    state: latest

- name: Install common utilties
  dnf:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"

- name: Add security group for virtual machine management
  group:
    name: libvirt
    state: present

- name: Add the user to the virtual machine management group
  user:
    name: "{{ ansible_user }}"
    append: true
    groups:
      - libvirt

- name: Make sure security access directory exists
  file:
    path: /etc/polkit-1/localauthority/50-local.d/
    state: directory
    mode: 0775

- name: Copy PKLA local access authority into place
  template:
    src: libvirt-libvirt-local-access.pkla.j2
    dest: /etc/polkit-1/localauthority/50-local.d/50-org.libvirt-libvirt-local-access.pkla
    mode: 0775

- name: Add google-chrome-stable repo
  template: 
    src: google-chrome-stable.j2
    dest: /etc/yum.repos.d/google-chrome.repo

- name: Install google chrome
  dnf:
    name: "google-chrome-stable"
    state: latest

- name: Remove unwanted packaged
  dnf:
    name: "{{ item }}"
    state: absent
  with_items: "{{ unwanted_packages }}"

  ####
  ## This seems to fall over because of an issue with the python-firewall module.
  ## (dnf unable to install a python-firewall package - not found)
  ####
  #- name: Make sure NFS/RPC is open in firewalld
  #firewalld:
  #  service: "{{ item }}"
  #  zone: FedoraWorkstation
  #  permanent: true
  #  state: enabled
  #with_items:
  #  - rpc-bind
  #  - nfs
  #  - mountd

- name: Make sure NFS/RPC is open in firewalld
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 2049 # NFS
    - 20049 # NFS

- name: restart services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - ufw
    - nfs
