---
- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install the 'Development tools' package group
  dnf:
    name: '@Development tools'
    state: present

- name: install the 'virtualization' package group
  dnf:
    name: '@virtualization'
    state: latest

- name: Install common utilties
  dnf:
    name: "{{ item }}"
    state: latest
  with_items: "{{ server_common_packages }}"

- name: Add google-chrome-stable repo
  shell: |
    cat << EOF > /etc/yum.repos.d/google-chrome.repo
    [google-chrome]
    name=google-chrome - \$basearch
    baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
    enabled=1
    gpgcheck=1
    gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
    EOF
  become: true

- name: Install google chrome
  dnf:
    name: "google-chrome-stable"
    state: latest

