---
- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install the 'Development tools' package group
  dnf:
    name: '@Development tools'
    state: present

- name: install the 'virtualization' package group
  dnf:
    name: '@virtualization'
    state: latest

- name: Install common utilties
  dnf:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"

- name: Add google-chrome-stable repo
  template: 
    src: google-chrome-stable.j2
    dest: /etc/yum.repos.d/google-chrome.repo

- name: Install google chrome
  dnf:
    name: "google-chrome-stable"
    state: latest

