---
- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install the 'Development tools' package group
  dnf:
    name: '@Development tools'
    state: present

- name: install the 'virtualization' package group
  dnf:
    name: '@virtualization'
    state: latest

- name: Install a specific vagrant version
  dnf:
    name: vagrant-1.9.1-3.fc27
    state: present

- name: Install common utilties
  dnf:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"

- name: Add security group for virtual machine management
  group:
    name: libvirt
    state: present

- name: Add the user to the virtual machine management group
  user:
    name: "{{ ansible_user }}"
    append: true
    groups:
      - libvirt

- name: Make sure security access directory exists
  file:
    path: /etc/polkit-1/localauthority/50-local.d/
    state: directory
    mode: 0775

- name: Copy PKLA local access authority into place
  template:
    src: libvirt-libvirt-local-access.pkla.j2
    dest: /etc/polkit-1/localauthority/50-local.d/50-org.libvirt-libvirt-local-access.pkla
    mode: 0775

- name: Add google-chrome-stable repo
  template: 
    src: google-chrome-stable.j2
    dest: /etc/yum.repos.d/google-chrome.repo

- name: Install google chrome
  dnf:
    name: "google-chrome-stable"
    state: latest

- name: Remove unwanted packaged
  dnf:
    name: "{{ item }}"
    state: absent
  with_items: "{{ unwanted_packages }}"
