---
- name: Install slack repo rpm
  dnf:
    name: https://downloads.slack-edge.com/linux_releases/slack-4.12.0-0.1.fc21.x86_64.rpm
    disable_gpg_check: yes
    state: present

- name: Install slack app
  dnf:
    name: slack
    disable_gpg_check: yes
    state: latest