---
- name: See if Slack is already installed
  shell: |
    flatpak list
  register: output

- name: Set if slack is installed already
  set_fact:
    slack_installed: true
  when: output.stdout | join('') is search(slack_search_name)

- name: Install Slack using Flakpak (via Shell) if it isn't installed already
  shell: |
    flatpak install flathub {{ slack_package_name }} -y > /dev/null 2>&1
  become: true
  become_user: root
  when: slack_installed != true

- name: Update Slack using Flakpak (via Shell) if it is already installed
  shell: |
    flatpak update {{ slack_package_name }} -y > /dev/null 2>&1
  become: true
  become_user: root
  when: slack_installed == true

#- name: Uninstall Slack using Flatpak (via Shell)
#  shell: |
#    flatpak uninstall {{ slack_package_name }}
#  become: true
#  become_user: root