---
- name: Install Arc themes & mac icons
  dnf:
    name: ['arc-theme', 'la-capitaine-icon-theme']
    state: latest

- name: Copy background images to pictures folder.
  shell: |
    mkdir -p /home/{{ ansible_user }}/Pictures/wallpapers
    cp -R opsjono.themes/files/* /home/{{ ansible_user }}/Pictures/wallpapers/
    chown {{ ansible_user }}:{{ ansible_user }} -R /home/{{ ansible_user }}/Pictures/wallpapers
