---
- name: Add the Papirus Icon repo
  template:
    src: papirus-icon-theme.repo.j2
    dest: /etc/yum.repos.d/papirus-icon-theme.repo

# TODO: Download & Install Mac shell theme.
# TODO: Install mac cursor themes to the icons directory.
# TODO: Gnome extensions to move clock the right, move notification, de-annoy the "app is ready" notifications, top bar transparency (27%), hide dash in overview?
- name: Install Arc themes, papirus & mac icons
  dnf:
    name: ['arc-theme', 'papirus-icon-theme', 'la-capitaine-icon-theme']
    state: latest

- name: Copy background images to pictures folder.
  shell: |
    mkdir -p /home/{{ ansible_user }}/Pictures/wallpapers
    cp -R opsjono.themes/files/* /home/{{ ansible_user }}/Pictures/wallpapers/
    chown {{ ansible_user }}:{{ ansible_user }} -R /home/{{ ansible_user }}/Pictures/wallpapers
