---
- name: Add the Moka Icon repo
  template:
    src: moka-icon-theme.repo.j2
    dest: /etc/yum.repos.d/moka-icon-theme.repo

- name: Add the Papirus Icon repo
  template:
    src: papirus-icon-theme.repo.j2
    dest: /etc/yum.repos.d/papirus-icon-theme.repo

- name: Install themes and icons
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - arc-theme
    - papirus-icon-theme
    - moka-icon-theme
