---
- name: Add the Papirus Icon repo
  template:
    src: papirus-icon-theme.repo.j2
    dest: /etc/yum.repos.d/papirus-icon-theme.repo

- name: Install Arc themes, papirus & mac icons
  dnf:
    name: ['arc-theme', 'papirus-icon-theme', 'la-capitaine-icon-theme']
    state: latest

- name: Ensure the theme folders exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  become: true
  become_user: root
  with_items:
    - "/opt/themes/pictures"
    - "/usr/share/icons/McMojave-cursors"
    - "/usr/share/icons/McMojave-cursors"

# TODO: Clone mac theme repo, install & tweak.

# Copy wallpapers
- name: Set variables for fedora wallpapers
  set_fact:
    files_from: "opsjono.themes/files/pictures/wallpapers/fedora"
    files_to: "/opt/themes/pictures/wallpapers/fedora"

- include_tasks: copy-files.yml

- name: Set variables for mac wallpapers
  set_fact:
    files_from: "opsjono.themes/files/pictures/wallpapers/mac"
    files_to: "/opt/themes/pictures/wallpapers/mac"

- include_tasks: copy-files.yml

- name: Set variables for mac icons
  set_fact:
    files_from: "opsjono.themes/files/pictures/icons"
    files_to: "/opt/themes/pictures/icons"

- include_tasks: copy-files.yml

- name: Install the mac cursor theme
  copy:
    src: "opsjono.themes/files/cursors/McMojave-cursors/"
    dest: "/usr/share/icons/McMojave-cursors/"
  become: true
  become_user: root
