---
- name: Add the Papirus Icon repo
  template:
    src: papirus-icon-theme.repo.j2
    dest: /etc/yum.repos.d/papirus-icon-theme.repo

# TODO: Download & Install Mac shell theme.
# TODO: Install mac cursor themes to the icons directory.
# TODO: Gnome extensions to move clock the right, move notification, de-annoy the "app is ready" notifications, top bar transparency (27%), hide dash in overview?
- name: Install Arc themes, papirus & mac icons
  dnf:
    name: ['arc-theme', 'papirus-icon-theme', 'la-capitaine-icon-theme']
    state: latest

- name: Set variables for fedora wallpapers
  set_fact:
    files_from: "opsjono.themes/files/pictures/wallpapers/fedora"
    files_to: "/home/{{ ansible_user }}/Pictures/wallpapers/fedora"

- include_tasks: copy-files.yml

- name: Set variables for mac wallpapers
  set_fact:
    files_from: "opsjono.themes/files/pictures/wallpapers/mac"
    files_to: "/home/{{ ansible_user }}/Pictures/wallpapers/mac"

- include_tasks: copy-files.yml

- name: Set variables for icons
  set_fact:
    files_from: "opsjono.themes/files/pictures/icons"
    files_to: "/home/{{ ansible_user }}/Pictures/icons"

- include_tasks: copy-files.yml