---
## @see https://medium.com/@ankurloriya/install-gnome-extension-using-command-line-736199be1cda
# TODO: Hide dash in overview or store & copy gnome-dash settings.
- name: Install Gnome extensions
  copy:
    src: "opsjono.gnome-extensions/files/"
    dest: "/usr/share/gnome-shell/extensions/"
  become: true
  become_user: root

- name: Activate gnome extensions
  command: "gnome-shell-extension-tool -e {{ item }}"
  with_items: "{{ extension_uuids }}"