---
# Install & Configure PhpStorm

- name: List installed packages
  shell: |
    flatpak list
  register: output
  changed_when: false

- name: Set if PHPStorm is installed already
  set_fact:
    phpstorm_installed: true
  when: output.stdout | join('') is search(phpstorm_package_name)

- name: Install PHPStorm using Flakpak (via Shell) if it isn't installed already (Takes a while)
  shell: |
    flatpak install {{ phpstorm_package_name }} -y > /dev/null 2>&1
  become: true
  become_user: root
  when: phpstorm_installed != true

- name: Update PHPStorm using Flakpak (via Shell) if it is already installed (May take a while)
  shell: |
    flatpak update {{ phpstorm_package_name }} -y > /dev/null 2>&1
  become: true
  become_user: root
  when: phpstorm_installed == true

- name: Ensure directory for the icon exists
  file:
    path: /opt/phpstorm
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
    state: directory

- name: Copy PhpStorm icon into place
  copy:
    src: icon.png
    dest: /opt/phpstorm/icon.png

- name: Install phpstorm.desktop file
  copy:
    src: phpstorm.desktop
    dest: /usr/share/applications/phpstorm.desktop

- name: Register desktop file
  command: update-desktop-database /usr/share/applications/
  become: true
  become_user: root
  changed_when: false

- name: Ensure PhpStorm preferences folder exists
  file:
    path: "/home/{{ ansible_user }}/.var/app/com.jetbrains.PhpStorm/config/JetBrains/PhpStorm{{ phpstorm_version }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  become: true
  become_user: "{{ ansible_user }}"

- name: Copy personal preferences to the PhpStorm directory
  copy:
    src: "opsjono.phpstorm/files/preferences/"
    dest: "/home/{{ ansible_user }}/.var/app/com.jetbrains.PhpStorm/config/JetBrains/PhpStorm{{ phpstorm_version }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
    directory_mode: true

- name: Set permissions on PhpStorm preferences directory
  shell: |
    chmod -R 775 "/home/{{ ansible_user }}/.var/app/com.jetbrains.PhpStorm/config/JetBrains/PhpStorm{{ phpstorm_version }}/"
  become: true
  become_user: "{{ ansible_user }}"