---
language: python
python: "2.7"

sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: centos
    version: 7
  # - distribution: centos
  #   version: 6 # package issue with mandb
  - distribution: fedora
    version: 25
  - distribution: ubuntu
    version: 16.04
  - distribution: ubuntu
    version: 14.04
  - distribution: ubuntu
    version: 12.04

before_install:
  - 'sudo docker run -it --name=ansible-rclone --privileged --detach --volume="${PWD}":/etc/ansible/roles/ansible-rclone:rw spikebyte/docker:latest-${distribution}-${version} bash'

script:
  # 1. Syntax check
  - "sudo docker exec ansible-rclone ansible-playbook /etc/ansible/roles/ansible-rclone/tests/test.yml -i tests/inventory --syntax-check"

  # 2. Run playbook to execute role
  - "sudo docker exec ansible-rclone ansible-playbook /etc/ansible/roles/ansible-rclone/tests/test.yml -i tests/inventory --connection=local"

  # 3. HERE, WRITE SOME TESTS to verify that your role has produced the desired
  # effect on the target system. Your tests should be bash commands that
  # complete with an exit status of 0 for a pass, and non-zero for a failure.
  #
  # This example tests whether 'hello' exists in /tmp/hello.txt.
  - >
    sudo docker exec ansible-rclone bash -c 'file /usr/sbin/rclone' | grep -q 'executable'
    && (echo 'Test for role result: pass' && exit 0)
    || (echo 'Test for role result: fail' && exit 1)

  # 4. Idempotence test (run playbook again to confirm nothing changes)
  - >
    sudo docker exec ansible-rclone ansible-playbook /etc/ansible/roles/ansible-rclone/tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications
    on_success: always
    on_failure: never
