---
ansible_distribution: RedHat
ansible_system: fedora
slack_base_url: https://slack.com/downloads/instructions/
slack_os: "{{ ansible_system | lower }}"
slack_download_url: "{{ slack_base_url }}{{ slack_distro }}?os={{ slack_os }}"

slack_html_src: "{{ slack_tmp_dir }}/slack-{{ slack_distro }}.html"

slack_package: "{{ slack_tmp_dir }}/slack-{{ slack_distro }}.{{ slack_package_format }}"
