---
common_packages:
  - thunderbird
  - gnome-terminal-nautilus
  - vim-enhanced
  - htop
  - iotop
  - pv
  - screen
  - git
  - gparted
  - tcpdump
  - rsync
  - xclip
  - remmina
  - openssh-askpass
  - gimp

  ## Vagrant and libvirt related
  - ruby-devel
  - gcc
  - libxslt-devel
  - libxml2-devel
  - libguestfs-tools-c
  - vagrant-libvirt

  ## Firewall (required for vagrant-shared folders)
  - python3-firewall
  - firewalld

    #  - build-essential
  - nfs-utils

  # Used to perform API requests
  - curl
  # Enables automation of programs and scripts that ask for user input
  - expect
  # Used to configure firewall rules
  - iptables
  - npm

  # Required for JetBrains apps to create desktop files
  - flatpak-xdg-utils

#  - steam

  # Extra's to add
  - ffmpeg-libs
  - fuse-exfat
  - gnome-tweak-tool
  - gnome-extensions-app
  - vlc
  - vlc-extras


unwanted_packages:
  - evolution
