---
common_packages:
  - thunderbird
  - vim
  - htop
  - iotop
  - pv
  - screen
  - git
  - tcpdump
  - rsync
  - xclip

  # Firewall stuff
  - python-firewall
  - firewalld
  - firewall-config

  ## Vagrant and libvirt related
  - qemu 
  - libvirt 
  - libvirt-devel 
  - ruby-devel 
  - gcc 
  - libxslt-devel 
  - libxml2-devel 
  - libguestfs-tools-c
  - vagrant-libvirt

    #  - build-essential
  - nfs-utils

  # Used to perform API requests
  - curl
  # Enables automation of programs and scripts that ask for user input
  - expect
  # Used to configure firewall rules
  - iptables
  # Ensures the server's clock is set properly
  - ntp
  # Required for running Ansible
  - libselinux-python
  # Required for MJML
  - npm

  - steam

  ## Stuff left to install:
  # rclone


unwanted_packages:
  - evolution
