---
common_packages:
  - thunderbird
  - vim-enhanced
  - htop
  - iotop
  - pv
  - screen
  - git
  - tcpdump
  - rsync
  - xclip
  - openssh-askpass
  - gimp

  ## Vagrant and libvirt related
#  - ruby-devel
#  - gcc
#  - libxslt-devel
#  - libxml2-devel
#  - libguestfs-tools-c
#  - vagrant-libvirt

  ## Firewall (required for vagrant-shared folders)
  - python3-firewall
  - firewalld

    #  - build-essential
  - nfs-utils
  - liveusb-creator

  # Used to perform API requests
  - curl
  # Enables automation of programs and scripts that ask for user input
  - expect
  # Used to configure firewall rules
  - iptables
  - npm

#  - steam

  # Extra's to add
  - vlc
  - vlc-extras

  # Gnome specific packages
  - gnome-terminal-nautilus
  - gnome-tweak-tool
  - gnome-extensions-app
  - gparted
  - guake

unwanted_packages:
  - evolution
