---
server_common_packages:
  - vim
  - htop
  - iotop
  - pv
  - screen
  - git
  - tcpdump
  - rsync
  - build-essential
  - nfs-common

  # Used to perform API requests
  - curl
  # Enables automation of programs and scripts that ask for user input
  - expect
  # Used to verify GPG signatures for mirrored packages
  - gnupg
  # Used to configure firewall rules
  - iptables
  # Used for documentation generation
  - markdown
  # Ensures the server's clock is set properly
  - ntp
  # Required to use the Ansible `expect` module
  - python-pexpect
  # Required for the apt_repository module
  - python-software-properties