---
- name: Install keybase repo rpm
  dnf:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    disable_gpg_check: yes
    state: present

- name: Install keybase app
  dnf:
    name: keybase
    disable_gpg_check: yes
    state: latest