---

- name: Add the Docker CE repo
  template:
    src: fedora-docker-ce.repo.j2
    dest: /etc/yum.repos.d/fedora-docker-ce.repo

- name: Remove Podman-docker
  dnf:
    name: ['podman', 'podman-docker']
    state: removed

- name: Install Docker CE, Docker CLI and Containerd.io
  dnf:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
    state: latest

- name: Add user to the docker user group.
  user:
    name: "{{ local_user.stdout }}"
    append: true
    groups: "docker"

# @see https://docs.docker.com/compose/cli-command/#install-on-linux
- name: Ensure the Docker CLI plugins directory exists/
  file:
    path: "/usr/local/lib/docker/cli-plugins"
    state: directory
  become: true
  become_user: root

- name: Ensure the Docker CLI plugins directory exists/
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64"
    dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
    owner: root
    group: root
    mode: 0775
  become: true
  become_user: root

- name: Make sure the Docker service is running and enabled on boot.
  service:
    name: docker
    state: started
    enabled: yes