---
- name: create download directory
  file:
    state: directory
    dest: "{{ postman_download_dir }}"

- name: Download Latest Version of Postman
  get_url:
    url: "{{ postman_zip_url }}"
    dest: "{{ postman_download_dir }}/{{ postman_zip_filename }}"
    force: yes
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: Install Latest version of Postman
  shell: |
    cp {{ postman_download_dir }}/{{ postman_zip_filename }} /opt
    tar -xvzf {{ postman_zip_filename }}
  args:
    chdir: /opt

- name: Install postman.desktop file
  template:
    src: postman.desktop.j2
    dest: /usr/share/applications/postman.desktop

- name: Symlink postman to /usr/local/bin
  file:
    src: /opt/Postman/app/Postman
    dest: /usr/local/bin/postman
    state: link

