---
- hosts: localhost
  name: Provision
  gather_facts: no
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo dnf update -y && sudo dnf install -y python python-dnf)
      changed_when: False
  become: true

  roles:
    - opsjono.package_installations
    - opsjono.gitkraken
