---
- hosts: localhost
  name: Provision
  gather_facts: no
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo dnf update -y && sudo dnf install -y python python-dnf)
      changed_when: False

    - name: get the username running the playbook
      become: false
      local_action: command whoami
      register: local_user
      changed_when: false
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  vars:
    - ansible_user: "{{ lookup('env','USER') }}"
    - ansible_os_family: 'RedHat'
    - ansible_architecture: 'x86_64'
    - ansible_distribution_version: '10.04'
    - ansible_distribution: 'RedHat'
    - ansible_distribution_major_version: '8'

  roles:
    - opsjono.package_installations # done
    - opsjono.themes # done
#    - opsjono.discord # Not needed
    - opsjono.gitkraken # done
    - opsjono.phpstorm # done
    - opsjono.datagrip # done
    - opsjono.mysql_workbench # done
    - opsjono.postman # done
    #- opsjono.skype # Not needed
    - opsjono.docker # done
    - opsjono.keybase # done
    #- opsjono.spotify # Not needed
    - opsjono.vpn # done
    - opsjono.slack # done

#    - opsjono.mjml
#    - azavea.terraform
#    - ghyde.virtualbox
#    - stefangweichinger.ansible-rclone
#    - geerlingguy.apache
#    - geerlingguy.redis
#    - geerlingguy.php
#    - role: geerlingguy.mysql
#      become: true
