---
- hosts: localhost
  name: Provision
  gather_facts: no
  pre_tasks:
    # TODO: Remove python2 usage and swap to python3 for everything
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo dnf update -y && sudo dnf install -y python python-dnf)
      changed_when: False

    # TODO: Python2 warning
    - name: get the username running the playbook
      become: false
      local_action: command whoami
      register: local_user
      changed_when: false
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  vars:
    - ansible_user: "{{ lookup('env','USER') }}"
    - ansible_os_family: 'RedHat'
    - ansible_architecture: 'x86_64'
    - ansible_distribution_version: '10.04'
    - ansible_distribution: 'RedHat'
    - ansible_distribution_major_version: '8'

  roles:
#    - opsjono.package_installations
    - opsjono.themes
#    - opsjono.cairo-dock
#    - opsjono.crontab
#    - opsjono.gnome-extensions
#    - opsjono.gitkraken
#    - opsjono.phpstorm
#    - opsjono.datagrip
#    - opsjono.postman
#    - opsjono.docker
#    - opsjono.nginx
#    - opsjono.keybase
#    - opsjono.vpn
#    - opsjono.slack

#    - opsjono.spotify
#    - opsjono.ssh
#    - opsjono.snapd
#    - opsjono.php-cs-fixer
#    - opsjono.nvidia
#    - opsjono.discord
#    - opsjono.mjml
#    - stefangweichinger.ansible-rclone
