---
- hosts: localhost
  name: Provision
  gather_facts: no
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo dnf update -y && sudo dnf install -y python python-dnf)
      changed_when: False
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  vars:
  - ansible_os_family: 'RedHat'
  - ansible_architecture: 'x86_64'

  roles:
    - opsjono.package_installations
    - opsjono.discord
    - opsjono.gitkraken
    - opsjono.phpstorm
    - jdauphant.atom
    - jgkim.atom_packages
    - opsjono.mysql_workbench
    - opsjono.mjml
    - avnes.slack
    - opsjono.spotify
    - opsjono.ckb-next
    - stefangweichinger.ansible-rclone
