---
- name: install gitkraken using snap
  command: "{{ item }}"
  become: true
  become_user: root
  with_items:
    - "snap install gtk-common-themes --beta"
    - "snap install gitkraken --beta"

###
# These are not required when using the snapd version of gitkraken
###
#- name: Copy GitKraken icon into place
#  copy:
#    src: icon.png
#    dest: /opt/gitkraken.png
#
#- name: Install gitkraken.desktop file
#  template:
#    src: gitkraken.desktop.j2
#    dest: /usr/share/applications/gitkraken.desktop
