---
- name: Install EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Slack
  package:
    name: "{{ slack_package }}"
    state: present

###
# Fix slack segfaulting on Fedora 29
#
# sudo dnf copr enable ghjm/glibc -y && sudo dnf update glibc -y --best --allowerasing
###

    #- name: Enable "ghjm/glibc" COPR
    #shell: |
    # dnf copr enable -y ghjm/glibc
    #become: true

    #- name: Update glibc
    #shell: |
    #sudo dnf update glibc -y --best --allowerasing
    #become: true
